### ISSUE TITLE
Have you idea about this plugin error?

### ISSUE THREAD

**Issue by Tarabakti** [NinevaStudios/MqttUtilities-UnrealEngine#1]
Certain time receive this error in Unreal log shell:

LogTemp: Error: MQTT => Connection error: The connection was lost.

if I already click in subscribe button, work but after 2-3 seconds this error message again 

Please help me

Emi

**Comment by tustanivsky** [comment]
Hello, maybe you can try to obtain some logs from your mqtt broker?

**Comment by Tarabakti** [comment]
Thank you very much, I fix the problem to setting qos=0 in subscribe event!
In this manner not disconnected

Good job!
Emiliano
